import {
  FaAws,
  FaBootstrap,
  FaNodeJs,
  FaReact,
  FaStripe,
} from "react-icons/fa";
import {
  SiC,
  SiCplusplus,
  SiCss3,
  SiCssmodules,
  SiExpress,
  SiFirebase,
  SiHtml5,
  SiMantine,
  SiMongodb,
  SiMongoose,
  SiMui,
  SiMysql,
  SiNetlify,
  SiNextdotjs,
  SiPostman,
  SiPython,
  SiRedis,
  SiRedux,
  SiSequelize,
  SiTailwindcss,
  SiTypescript,
  SiVercel,
} from "react-icons/si";
import { TbBrandJavascript, TbBrandVscode, TbBrandVite } from "react-icons/tb";

import { CgFramer } from "react-icons/cg";

export const techSkills = [
  {
    name: "C",
    desc: "A general-purpose, imperative computer programming language. Known for its efficiency and being the basis for many other programming languages.",
    icon: SiC,
    color: "#A8B9CC",
    type: "Languages",
  },
  {
    name: "C++",
    desc: "An extension of the C programming language, offering additional features like object-oriented programming, classes, and templates.",
    icon: SiCplusplus,
    color: "#649AD2",
    type: "Languages",
  },
  {
    name: "JavaScript",
    desc: "A versatile programming language primarily used for creating interactive effects within web browsers, enabling dynamic content and user interaction on web pages.",
    icon: TbBrandJavascript,
    color: "#F7DF1E",
    type: "Languages",
  },
  {
    name: "TypeScript",
    desc: "A versatile programming language primarily used for creating interactive effects within web browsers, enabling dynamic content and user interaction on web pages.",
    icon: SiTypescript,
    color: "#3178C6",
    type: "Languages",
  },
  {
    name: "Python",
    desc: "An interpreted high-level programming language for general-purpose programming, known for its simplicity, readability, and large standard library.",
    icon: SiPython,
    color: "#3572A5",
    type: "Languages",
  },
  {
    name: "HTML",
    desc: "HTML(HyperText Markup Language )is standard markup language for creating web pages and web applications. It defines the structure and content of web pages.",
    icon: SiHtml5,
    color: "#E34F26",
    type: "Frontend",
  },
  {
    name: "CSS",
    desc: "CSS(Cascading Style Sheets) is used to style the presentation of HTML and XML documents, defining the layout, colors, fonts, and other visual aspects of web pages.",
    icon: SiCss3,
    color: "#1572B6",
    type: "Frontend",
  },
  {
    name: "CSS module",
    desc: "A modular approach to writing and organizing CSS by scoped naming and local scoping, preventing style conflicts.",
    icon: SiCssmodules,
    color: "#DB7093",
    type: "Frontend",
  },
  {
    name: "Material-UI",
    desc: "A popular React UI framework offering a wide range of pre-built components, designed to follow the Material Design specification.",
    icon: SiMui,
    color: "#0081CB",
    type: "Frontend",
  },
  {
    name: "React.js",
    desc: "A popular JavaScript library for building user interfaces, developed by Facebook. It allows developers to create reusable UI components.",
    icon: FaReact,
    color: "#61DAFB",
    type: "Frontend",
  },
  {
    name: "Next.js",
    desc: "A React framework that enables server-side rendering and helps build production-ready React applications with ease.",
    icon: SiNextdotjs,
    color: "#000000",
    type: "Frontend",
  },
  {
    name: "TailwindCSS",
    desc: "A utility-first CSS framework that provides low-level utility classes to build designs directly in HTML markup.",
    icon: SiTailwindcss,
    color: "#38B2AC",
    type: "Frontend",
  },
  {
    name: "Mantine UI",
    desc: "A React component library offering ready-to-use components to build modern web applications.",
    icon: SiMantine,
    color: "#0088cc",
    type: "Frontend",
  },
  {
    name: "Framer Motion",
    desc: "A React animation library for creating fluid animations and expressive transitions in user interfaces.",
    icon: CgFramer,
    color: "",
    type: "Frontend",
  },
  {
    name: "BootStrap",
    desc: "A front-end framework for building responsive and mobile-first websites, providing pre-built components and styles.",
    icon: FaBootstrap,
    color: "#7952B3",
    type: "Frontend",
  },
  {
    name: "NodeJs",
    desc: "A JavaScript runtime that allows the execution of JavaScript code server-side, enabling the development of scalable network applications.",
    icon: FaNodeJs,
    color: "#68A063",
    type: "Backend",
  },
  {
    name: "MongoDB",
    desc: "A NoSQL database system that uses a document-oriented data model, storing data in flexible, JSON-like documents.",
    icon: SiMongodb,
    color: "#4DB33D",
    type: "Backend",
  },
  {
    name: "SQL",
    desc: "SQL(Structured Query Language) is a language used to manage and manipulate relational databases.",
    icon: SiMysql,
    color: "#336791",
    type: "Backend",
  },
  {
    name: "Mongoose",
    desc: "An Object Data Modeling (ODM) library for MongoDB and Node.js, providing a schema-based solution for modeling application data.",
    icon: SiMongoose,
    color: "#880000",
    type: "Backend",
  },
  {
    name: "Express.js",
    desc: "A minimal and flexible Node.js web application framework, often used as the backend framework for web applications.",
    icon: SiExpress,
    color: "#000000",
    type: "Backend",
  },
  {
    name: "Redux",
    desc: "A predictable state container for JavaScript applications, commonly used with React for managing application state.",
    icon: SiRedux,
    color: "#764ABC",
    type: "Frontend",
  },
  {
    name: "Sequelize",
    desc: "",
    icon: SiSequelize,
    color: "#52B0E7",
    type: "Backend",
  },
  {
    name: "Redis",
    desc: "",
    icon: SiRedis,
    color: "#DC382D",
    type: "Backend",
  },

  {
    name: "VS Code",
    desc: "A predictable state container for JavaScript applications, commonly used with React for managing application state.",
    icon: TbBrandVscode,
    color: "#007ACC",
    type: "Tools",
  },
  {
    name: "Postman",
    desc: " A collaboration platform for API development, allowing users to design, test, and document APIs.",
    icon: SiPostman,
    color: "#FF6C37",
    type: "Tools",
  },
  {
    name: "AWS",
    desc: "Amazon Web Services, a cloud computing platform providing a suite of services for building, deploying, and managing applications and workloads in the cloud.",
    icon: FaAws,
    color: "#FF9900",
    type: "Tools",
  },
  {
    name: "stripe",
    desc: "A payment processing platform that allows businesses to accept payments and manage online transactions securely.",
    icon: FaStripe,
    color: "#6772E5",
    type: "Tools",
  },
  {
    name: "Firebase",
    desc: "A platform developed by Google for building mobile and web applications, offering various tools and services like hosting, databases, authentication, and more.",
    icon: SiFirebase,
    color: "#FFCA28",
    type: "Tools",
  },
  {
    name: "Vercel",
    desc: "A cloud platform for static sites and serverless functions, enabling seamless deployment and hosting of web projects.",
    icon: SiVercel,
    color: "#000000",
    type: "Tools",
  },
  {
    name: "Netlify",
    desc: "A platform providing hosting and serverless backend services for web applications, emphasizing continuous deployment and developer workflow.",
    icon: SiNetlify,
    color: "#00C7B7",
    type: "Tools",
  },

  // {
  //   name: "Vite",
  //   desc: "",
  //   icon: TbBrandVite,
  //   color: "#00C7B7",
  //   type: "Tools",
  // },
];
